// Generated by CoffeeScript 1.6.3
(function() {
  var window;

  window = typeof exports !== "undefined" && exports !== null ? exports : this;

  window.getDeviceInfo = function() {
    return [
      {
        name: 'First Arduino board ',
        image: 'http://www.fillmurray.com/g/100/102',
        status: 'status',
        id: '1',
        otherDetailedinfomation: 'what ever other details you many need',
        pins: [
          {
            image: 'http://www.fillmurray.com/g/100/101',
            id: '3',
            activemode: 'Pull Up',
            currentColor: '#FF3300',
            inAdvancedMode: false,
            otherDetailedinfomation: 'what ever other details you many need',
            name: 'Pin 1',
            status: 'status',
            mapping: 'mapping',
            subpinsImage: 'http://fillmurray.com/g/200/201',
            subpins: [
              {
                image: 'http://fillmurray.com/g/200/203',
                id: '2',
                mapping: 'mapping',
                activemode: 'Pull Up',
                currentColor: '#FF3300',
                otherDetailedinfomation: 'what ever other details you many need',
                name: 'name',
                status: 'status'
              }
            ]
          }, {
            image: 'http://www.fillmurray.com/g/100/102',
            id: '4',
            activemode: 'Pull Up',
            currentColor: '#CC6600',
            inAdvancedMode: true,
            otherDetailedinfomation: 'what ever other details you many need',
            name: 'Pin 2',
            status: 'status',
            mapping: 'mapping',
            subpinsImage: 'http://fillmurray.com/g/200/201',
            subpins: [
              {
                image: 'http://fillmurray.com/g/200/203',
                id: '2',
                mapping: 'mapping',
                activemode: 'Pull Down',
                currentColor: '#CC6600',
                otherDetailedinfomation: 'what ever other details you many need',
                name: 'name',
                status: 'status'
              }
            ]
          }, {
            image: 'http://www.fillmurray.com/g/100/105',
            id: '5',
            activemode: 'Pull Up',
            currentColor: '#FF3300',
            otherDetailedinfomation: 'what ever other details you many need',
            name: 'Pin 3',
            status: 'status',
            mapping: 'mapping',
            subpinsImage: 'http://fillmurray.com/g/200/201',
            subpins: [
              {
                image: 'http://fillmurray.com/g/200/203',
                id: '2',
                mapping: 'mapping',
                activemode: 'Pull Up',
                otherDetailedinfomation: 'what ever other details you many need',
                name: 'name',
                status: 'status'
              }
            ]
          }, {
            image: 'http://www.fillmurray.com/g/100/104',
            id: '6',
            activemode: 'Pull Up',
            currentColor: '#FF3300',
            otherDetailedinfomation: 'what ever other details you many need',
            name: 'Pin 4',
            status: 'status',
            mapping: 'mapping',
            subpinsImage: 'http://fillmurray.com/g/200/201',
            subpins: [
              {
                image: 'http://fillmurray.com/g/200/203',
                id: '2',
                mapping: 'mapping',
                activemode: 'Pull Up',
                otherDetailedinfomation: 'what ever other details you many need',
                name: 'name',
                status: 'status'
              }
            ]
          }
        ]
      }, {
        name: 'second Arduino board ',
        image: 'http://www.fillmurray.com/g/100/103',
        status: 'status',
        id: '2',
        otherDetailedinfomation: 'what ever other details you many need',
        pins: [
          {
            image: 'http://www.fillmurray.com/g/100/101',
            id: '3',
            activemode: 'Pull Up',
            currentColor: '#FF3300',
            otherDetailedinfomation: 'what ever other details you many need',
            name: 'Pin 1',
            status: 'status',
            mapping: 'mapping',
            subpinsImage: 'http://fillmurray.com/g/200/201',
            subpins: [
              {
                image: 'http://fillmurray.com/g/200/203',
                id: '2',
                mapping: 'mapping',
                activemode: 'Pull Up',
                otherDetailedinfomation: 'what ever other details you many need',
                name: 'name',
                status: 'status'
              }
            ]
          }
        ]
      }
    ];
  };

}).call(this);
