// Generated by CoffeeScript 1.6.3
(function() {
  var app, fs, generateChartData, getUpdateData, io,  server, __dirname;

  app = require('express')();

  app.use(require('express').static(__dirname + '../../'));

  app.get('/', function(req, res) {
    console.log('recieved request');
    return fs.readFile(__dirname + '../index.html', function(err, data) {
      if (err) {
        console.log('error');
        res.writeHead(500);
        return res.end('error loading index.html');
      } else {
        console.log('success');
        res.writeHead(200);
        return res.end(data);
      }
    });
  });

  webserver = require('http').createServer(app);
  chartserver = require('http').createServer(app);
  graphserver = require('http').createServer(app);

  
  fs = require('fs');

  __dirname = '';

  webserver.listen(8000, function() {
    return console.log('Web listening');
  });

  chartserver.listen(3000, function() {
    return console.log('Chart socket listening');
  });

  chart_io = require('socket.io')(chartserver);

  graphserver.listen(4000, function() {
    return console.log('Graph socket listening');
  });

  graph_io = require('socket.io')(graphserver);



  generateChartData = function() {
    var lineChartData;
    return lineChartData = [
      {
        label: 'test1',
        datapoints: []
      }, {
        label: 'test2',
        datapoints: []
      }, {
        label: 'test3',
        datapoints: []
      }, {
        label: 'test4',
        datapoints: []
      }
    ];
  };

getUpdateData = function(timestamp, socket) {
    return fs.readFile('./data.json', 'utf8', function(err, data) {
      var nodeDataList;
      if (err) {
        return console.log(err);
      } else {
        nodeDataList = JSON.parse(data);
        return socket.emit('update', nodeDataList);
      }
    });
  };

chart_io.on('connection', function(socket) {
    var int, timestamp;
    timestamp = 1383230821680;
    /* this is just for testing it needs to be compiled with actual state of each pin  this could be done via a local database*/

    socket.emit('init', generateChartData());
    console.log('connected');
    int = setInterval(function() {
      timestamp += 1000;
      getUpdateData(timestamp, socket);
//      return console.log('update Sent');
        return;
    }, 1000);
    socket.on('updateComponent', function(data) {});
    return socket.on('disconnect', function() {
      return clearInterval(int);
    });
  });

var nw_data; 

/*initializing the websockets communication , server instance has to be sent as the argument */
graph_io.sockets.on("connection",function(socket){
      
      //Clients will join the server in rooms/channels
      //rpsock is the routing processor socket
      //browswersock is the web browser socket
      socket.on('join', function (data) {
        console.log(data.socketid);
        socket.join(data.socketid);
        //If browser just joined - send it the DOGE network info
        if (data.socketid === 'browsersock') {
          graph_io.to('browsersock').emit("load_network",nw_data);
          console.log('browser connected - sending load n/w data');

        }
 
      });
      var ack_to_client = {
          data:"Server Received the message"
        }
      graph_io.to('browsersock').emit(JSON.stringify(ack_to_client));
  
    console.log('Socket.io Connection with the client established');
    
    //Handle incoming messages from the browser
    socket.on("message",function(data,callback){
        console.log('Received request from browser:');
        console.log(data);
        graph_io.to('rpsock').emit(data);
    }); 

    //Routing Processor will send the network info as a 'load network message'
    //Handle load network message to render network on vis
    socket.on("load_network",function(data){
        console.log("Received load network");
        nw_data = data;
        //Debug
        // data = JSON.parse(data);
        // console.log(data);
        var ack_to_client = {
          data:"Server Received the message"
        }
        graph_io.to('rpsock').emit('ack',JSON.stringify(ack_to_client));
    });

    socket.on("confirm",function(data){
        graph_io.to('browsersock').emit("confirm",data);
        console.log("Received confirmation from RP:");
       // Debug
         data = JSON.parse(data);
         console.log(data);
    });
 
});
}).call(this);
