all:
	gcc -c -Os defines.c -o def_s
	gcc -c -O3 defines.c -o def_3
	gcc -c -O2 defines.c -o def_2
	gcc -c -O1 defines.c -o def_1
	gcc -c -O0 defines.c -o def_0
	
	gcc -c -Os -S defines.c -o def_asm_s
	gcc -c -O3 -S defines.c -o def_asm_3
	gcc -c -O2 -S defines.c -o def_asm_2
	gcc -c -O1 -S defines.c -o def_asm_1
	gcc -c -O0 -S defines.c -o def_asm_0
	

	gcc -c -Os lists_function.c -o list_f_s
	gcc -c -O3 lists_function.c -o list_f_3
	gcc -c -O2 lists_function.c -o list_f_2
	gcc -c -O1 lists_function.c -o list_f_1
	gcc -c -O0 lists_function.c -o list_f_0

	gcc -c -Os -S lists_function.c -o list_f_asm_s
	gcc -c -O3 -S lists_function.c -o list_f_asm_3
	gcc -c -O2 -S lists_function.c -o list_f_asm_2
	gcc -c -O1 -S lists_function.c -o list_f_asm_1
	gcc -c -O0 -S lists_function.c -o list_f_asm_0
	
	gcc -c -Os lists_macro.c -o list_m_s
	gcc -c -O3 lists_macro.c -o list_m_3
	gcc -c -O2 lists_macro.c -o list_m_2
	gcc -c -O1 lists_macro.c -o list_m_1
	gcc -c -O0 lists_macro.c -o list_m_0

	gcc -c -Os -S lists_macro.c -o list_m_asm_s
	gcc -c -O3 -S lists_macro.c -o list_m_asm_3
	gcc -c -O2 -S lists_macro.c -o list_m_asm_2
	gcc -c -O1 -S lists_macro.c -o list_m_asm_1
	gcc -c -O0 -S lists_macro.c -o list_m_asm_0
